@startuml
start

:Registered or guest user
goes to available word lists site;

:User chooses a word list
that they want to learn
(start quiz and add to my lists button);

if (Is the user registered?) then (yes)
    if (Which action?) then (Start learning)
    else (Add to my lists)

        :User goes to the own lists site;

        :Starts learning the previously
        chosen shared list;

    endif
else (no)
endif

:User gets redirected
to the quiz site;

repeat
    if (First quiz round?) then (yes)

        :App shows some information about
        the quiz (quiz starter site)
        until the quiz loads;

    else (no)

        :App shows statistics
        about this quiz round;

    endif;
    :App shows current overall progress
    (after it loads);

    :Quizzes are loaded from the backend;

    :User goes through 5-15 flashcards and questions;

    :The correctness of the answer is sent to backend
    and the progress is saved;
repeat while (learning progress ) is (<100%)
-> equals 100%;

:App shows congratulations message;

:User gets redirected to the own lists site;

:User optionally removes the word list
from the own lists site;

stop
@enduml