on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        sudo docker build -t vocabulary-srv -f Dockerfile --build-arg COMMIT_HASH="$(git rev-parse HEAD)" .
    - name: Tag and upload docker image
      env: # Or as an environment variable
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | sudo docker login --username robertradnai --password-stdin
        sudo docker tag vocabulary_srv robertradnai/vocabulary_srv:"$(git branch --show-current)"
        sudo docker push robertradnai/vocabulary_srv:"$(git branch --show-current)"
