on:
  push:
    branches: [ main, develop, develop_workflow ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make build
    - name: Tag and upload docker image
      env: # Or as an environment variable
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        echo $DOCKERHUB_TOKEN | sudo docker login --username $DOCKERHUB_USERNAME --password-stdin
        make publish DOCKER_REPOSITORY=$DOCKERHUB_USERNAME
